// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gxlqhoqsnnzqauynrzen.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4bHFob3Fzbm56cWF1eW5yemVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNTQ3NjYsImV4cCI6MjA2OTkzMDc2Nn0.QFjashuTeudMb0QR99VKSTKVjLW4qDmf_ax_RsALibY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});